<?php
define('BFRONT_DAILY_ARCHVIES', __('Daily Archives', 'bfront'));
define('BFRONT_MONTHLY_ARCHIVES', __('Monthly Archives', 'bfront'));
define('BFRONT_YEARLY_ARCHIVES', __('Yearly Archives', 'bfront'));
define('BFRONT_BLOG_ARCHIVES', __('Blog Archives', 'bfront'));
define('BFRONT_MOST_USED_CATEGORIES', __('Most Used Categories', 'bfront'));
define('BFRONT_TRY_LOOKING_MONTHLY_ARCHIVES', __('Try Looking Monthly Archives', 'bfront'));
define('BFRONT_OLDER_POSTS', __('&larr; Older Posts', 'bfront'));
define('BFRONT_NEWER_POSTS', __('Newer posts &rarr;', 'bfront'));
define('BFRONT_RETURN_TO_PREVIUS', __('Return to %s', 'bfront'));
define('BFRONT_BY_AUTHOR', __('By %2$s', 'bfront'));
define('BFRONT_VIEW_ALL_POST_BY', __('View all posts by %s', 'bfront'));
define('BFRONT_PUBLISHED_BY_AUTHOR', __('Published %2$s', 'bfront'));
define('BFRONT_FULL_SIZE_IS_PIXEL', __('Full size is %s pixels', 'bfront'));
define('BFRONT_LINK_TO_FULL_SIZE', __('Link to full-size image', 'bfront'));
define('BFRONT_EDIT', __('Edit', 'bfront'));
define('BFRONT_BOOKMARK_THE', __('Bookmark the', 'bfront'));
define('BFRONT_PERMALINK', __('&nbsp;permalink', 'bfront'));
define('BFRONT_PAGES_COLON', __('Pages:', 'bfront'));
define('BFRONT_AUTHOR_ARCHIVES', __('All posts by : %s', 'bfront'));
define('BFRONT_ABOUT_AUTHOR', __('About %s', 'bfront'));
define('BFRONT_HOME', __('Home', 'bfront'));
define('BFRONT_SORRY_NO_POST_MATCHED_YOUR_CRETERIA', __('Sorry no post matched your criteria', 'bfront'));
define('BFRONT_PRIMARY_WIDGET', __('Primary Widget Area', 'bfront'));
define('BFRONT_THE_PRIMARY_WIDGET', __('The primary widget area', 'bfront'));
define('BFRONT_SECONDRY_WIDGET', __('Secondary Widget Area', 'bfront'));
define('BFRONT_THE_SECONDRY_WIDGET', __('The secondary widget area', 'bfront'));
define('BFRONT_FIRST_FOOTER_WIDGET', __('First Footer Widget Area', 'bfront'));
define('BFRONT_THE_FIRST_FOOTER_WIDGET', __('The first footer widget area', 'bfront'));
define('BFRONT_SECONDRY_FOOTER_WIDGET', __('Second Footer Widget Area', 'bfront'));
define('BFRONT_THE_SECONDRY_FOOTER_WIDGET', __('The second footer widget area', 'bfront'));
define('BFRONT_THIRD_FOOTER_WIDGET', __('Third Footer Widget Area', 'bfront'));
define('BFRONT_THE_THIRD_FOOTER_WIDGET', __('The third footer widget area', 'bfront'));
define('BFRONT_FOURTH_FOOTER_WIDGET', __('Fourth Footer Widget Area', 'bfront'));
define('BFRONT_THE_FOURTH_FOOTER_WIDGET', __('The fourth footer widget area', 'bfront'));
define('BFRONT_MAIN_MENU', __('Main Menu', 'bfront'));
define('BFRONT_CATEGORIES', __('Categories', 'bfront'));
define('BFRONT_ARCHIVES', __('Archives', 'bfront'));
define('BFRONT_CONTACT_US', __('Contact Us', 'bfront'));
define('BFRONT_LOCATION_MAP', __('Location Map', 'bfront'));
